"""update slice dashboard

Revision ID: 458541ac00eb
Revises: 1296d28ec131
Create Date: 2017-03-16 13:32:24.731632

"""

# revision identifiers, used by Alembic.
revision = '458541ac00eb'
down_revision = '1296d28ec131'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('department', sa.Text(), nullable=True))
    op.add_column('slices', sa.Column('department', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slices', 'department')
    op.drop_column('dashboards', 'department')
    # ### end Alembic commands ###
