"""add dialy number table

Revision ID: 844b75f5aa4f
Revises: 458541ac00eb
Create Date: 2017-03-31 15:30:15.110806

"""

# revision identifiers, used by Alembic.
revision = '844b75f5aa4f'
down_revision = '458541ac00eb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obj_type', sa.String(length=32), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('dt', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_number')
    # ### end Alembic commands ###
