"""add database_acount

Revision ID: b07fd71fd00c
Revises: c377b998ae19
Create Date: 2017-04-20 13:07:36.429052

"""

# revision identifiers, used by Alembic.
revision = 'b07fd71fd00c'
down_revision = 'c377b998ae19'

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.encrypted import EncryptedType

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('database_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', EncryptedType(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['dbs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('daily_number', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_number', 'user_id')
    op.drop_table('database_account')
    # ### end Alembic commands ###
